version: 0.1


phases:
  install:
    commands:
      - echo nothing to install...
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo no pre_build commands...
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - npm install
      - npm run build
      - echo nothing to build yet...
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo no post build activity
artifacts:
  files:
      - index.html
      - favicon.ico
      - styles/*
      - images/*
      - dist/bundle.js
